/**
 * Analytics conversion tracking helpers for Jusi H2O
 * Generated by Faxstrive SEO Bot — Phase 5 Analytics & Conversion
 *
 * Usage:
 *   import { trackFormSubmit, trackPhoneClick, trackCTAClick } from '@/lib/analytics';
 *
 *   // In form onSubmit handler:
 *   trackFormSubmit('contact-form');
 *
 *   // On phone link click:
 *   trackPhoneClick('6157812339');
 *
 *   // On CTA button click:
 *   trackCTAClick('hero-get-quote');
 */

declare global {
  interface Window {
    dataLayer?: Array<Record<string, unknown>>;
    gtag?: (...args: unknown[]) => void;
  }
}

function pushEvent(eventName: string, params: Record<string, unknown> = {}) {
  // GTM dataLayer push
  if (typeof window !== 'undefined' && window.dataLayer) {
    window.dataLayer.push({ event: eventName, ...params });
  }

  // GA4 gtag event
  if (typeof window !== 'undefined' && window.gtag) {
    window.gtag('event', eventName, params);
  }
}

/** Track form submission */
export function trackFormSubmit(formName: string, formData?: Record<string, unknown>) {
  pushEvent('form_submit', {
    form_name: formName,
    ...formData,
  });
  pushEvent('generate_lead', {
    source: formName,
    value: 0,
    currency: 'USD',
  });
}

/** Track phone number click */
export function trackPhoneClick(phoneNumber?: string) {
  pushEvent('phone_call_click', {
    phone_number: phoneNumber || '+18133030515',
    link_url: `tel:${phoneNumber || '+18133030515'}`,
  });
}

/** Track CTA button click */
export function trackCTAClick(ctaName: string, ctaLocation?: string) {
  pushEvent('cta_click', {
    cta_name: ctaName,
    cta_location: ctaLocation || 'unknown',
  });
}

/** Track appointment/quote request */
export function trackQuoteRequest(service?: string) {
  pushEvent('get_quote', {
    service: service || 'general',
  });
  pushEvent('generate_lead', {
    source: 'quote_request',
    service: service || 'general',
  });
}
