import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://jusih2o.com";
  const lastModified = new Date("2026-03-18");

  return [
    { url: baseUrl, lastModified, changeFrequency: "weekly", priority: 1 },
    { url: `${baseUrl}/services`, lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/contact`, lastModified, changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/services/water-softeners`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/water-filtration`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/reverse-osmosis`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/water-testing`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/well-water`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/water-heater-installation`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/leak-repair`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/commercial-plumbing`, lastModified, changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/services/jusicare`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/about`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/testimonials`, lastModified, changeFrequency: "weekly", priority: 0.7 },
    { url: `${baseUrl}/service-area`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/before-after`, lastModified, changeFrequency: "monthly", priority: 0.7 },
    { url: `${baseUrl}/gallery`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/faq`, lastModified, changeFrequency: "monthly", priority: 0.6 },
    { url: `${baseUrl}/privacy-policy`, lastModified, changeFrequency: "yearly", priority: 0.3 },
    { url: `${baseUrl}/terms-of-service`, lastModified, changeFrequency: "yearly", priority: 0.3 },
    { url: `${baseUrl}/blog`, lastModified, changeFrequency: "weekly", priority: 0.7 },
      {
      url: `${baseUrl}/`,
      lastModified: new Date('2026-04-05'),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
  
    { url: 'https://jusih2o.com/articles/water-softener-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/whole-house-filtration-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/reverse-osmosis-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/water-filtration-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/water-testing-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/water-treatment-cost-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/water-softener-vs-water-conditioner', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/winter-water-tips-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/articles/summer-water-guide-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://jusih2o.com/water-softener-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-softener-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-softener-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-softener-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-softener-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment-in-hillsborough-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment-in-pinellas-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment-in-sarasota-county-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment-in-tampa-bay-fl', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment-in-florida', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-softener', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/whole-house-filtration', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/reverse-osmosis', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-filtration', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-testing', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/water-treatment', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://jusih2o.com/well-water-treatment', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 }
  ];
}



